package actions

import (
	"asa-server/internal/appconfig"
	cfgpkg "asa-server/internal/config"
	"asa-server/internal/installer"
	"asa-server/internal/runner"
	"asa-server/pkg/logger"
	"bufio"
	"context"
	"fmt"
	"os"
	"runtime"
	"strings"

	"github.com/urfave/cli/v3"
)

// SetupCommand 是 docs/LINUX_COMPATIBILITY_PLAN.md §10.5 G4 的 `asa-server setup`：
// Linux 上的首次引导入口，交互 + 非交互两种模式，串联 BaseDir 选择 → umu/GE-Proton
// 运行时 → SteamCMD → ARK 本体安装。Windows 上直接报错，指向 Fyne GUI 首次启动
// 向导（见 §10.7「首次启动向导做的事都必须有 CLI 或配置等价物」）。不拆
// _windows.go/_linux.go：下面的逻辑本身在两平台都能编译，只有一处 runtime.GOOS
// 分支，不涉及任何平台专属 API。
func SetupCommand() *cli.Command {
	return &cli.Command{
		Name: "setup",
		Usage: "Linux 首次引导：BaseDir → umu/GE-Proton 运行时 → SteamCMD → ARK 本体" +
			"（Windows 请用 GUI 首次启动向导）",
		Flags: []cli.Flag{
			&cli.BoolFlag{
				Name: "non-interactive",
				Usage: "非交互模式：不提示任何输入，缺少必要参数直接报错退出" +
					"（配合 --basedir 用于脚本/systemd 场景）",
			},
			&cli.StringFlag{
				Name:  "basedir",
				Usage: "数据目录。交互模式下留空会提示输入；非交互模式下必须提供，除非 config.yaml 已经配置过",
			},
		},
		Action: ActionSetup,
	}
}

func ActionSetup(ctx context.Context, cmd *cli.Command) error {
	if runtime.GOOS != "linux" {
		return fmt.Errorf("setup 命令仅在 Linux 上可用；Windows 请直接运行 GUI，首次启动会弹出同样的数据目录选择向导")
	}

	nonInteractive := cmd.Bool("non-interactive")
	flagBaseDir := strings.TrimSpace(cmd.String("basedir"))

	fmt.Println("=== ASA Server Manager 首次引导 ===")

	if problems := runner.Preflight(); len(problems) > 0 {
		fmt.Println("宿主依赖自检发现以下问题（不阻断继续，但对应功能可能起不来）：")
		for _, p := range problems {
			if p.Fix != "" {
				fmt.Printf("  - [%s] %s（修复建议：%s）\n", p.Name, p.Detail, p.Fix)
			} else {
				fmt.Printf("  - [%s] %s\n", p.Name, p.Detail)
			}
		}
	} else {
		fmt.Println("宿主依赖自检：通过")
	}

	baseDir, err := resolveSetupBaseDir(flagBaseDir, nonInteractive)
	if err != nil {
		return err
	}

	if baseDir != cfgpkg.BaseDir {
		fmt.Printf("正在应用新的数据目录: %s\n", baseDir)
		cfgpkg.BaseDir = baseDir
		if err := cfgpkg.EnsureDirectories(baseDir); err != nil {
			return fmt.Errorf("创建数据目录失败: %w", err)
		}
		logger.InitLoggerWithBaseDir(baseDir)
	}

	appCfg := appconfig.Get()
	runner.Configure(runner.Config{
		Runtime:       appCfg.Linux.Runtime,
		UmuVersion:    appCfg.Linux.UmuVersion,
		ProtonVersion: appCfg.Linux.ProtonVersion,
		PrefixMode:    appCfg.Linux.PrefixMode,
		PrefixDir:     appCfg.Linux.PrefixDir,
		AutoDownload:  appCfg.Linux.AutoDownload,
		GameID:        appCfg.Linux.GameID,
		BaseDir:       baseDir,
	})

	fmt.Println("正在准备 umu/GE-Proton 运行时（首次运行需要下载，可能需要几分钟）...")
	if err := runner.EnsureRuntime(ctx, os.Stdout); err != nil {
		return fmt.Errorf("准备 Wine/Proton 运行时失败: %w", err)
	}

	fmt.Println("正在下载/更新 SteamCMD...")
	if err := installer.DownloadAndExtractSteamCmd(ctx, os.Stdout); err != nil {
		return fmt.Errorf("安装 SteamCMD 失败: %w", err)
	}

	fmt.Println("正在下载/更新 ARK 服务端本体（体积较大，请耐心等待）...")
	if err := installer.DownloadAndUpdateArkServer(ctx, os.Stdout); err != nil {
		return fmt.Errorf("安装 ARK 服务端本体失败: %w", err)
	}

	fmt.Println("正在验证服务端安装...")
	if err := installer.VerifyServerInstallation(ctx, false); err != nil {
		return fmt.Errorf("验证服务端安装失败: %w", err)
	}

	fmt.Println()
	fmt.Println("=== 引导完成 ===")
	fmt.Printf("数据目录: %s\n", baseDir)
	fmt.Println("接下来可以：")
	fmt.Println("  asa-server service install   # 安装为 systemd 服务")
	fmt.Println("  asa-server cert install       # 安装本地 HTTPS 证书（需要 sudo）")
	fmt.Println("  asa-server user add           # 创建管理员账号（如需开启鉴权）")
	fmt.Println("  asa-server api                # 直接前台启动，验证一下也行")
	return nil
}

// resolveSetupBaseDir 决定这次引导用哪个 BaseDir：
//   - WasConfigAutoGenerated() 为 false：main.go 启动时那次 Load 读到的是已经存在
//     的 config.yaml（可能是重复运行 setup，或者手动配置过），直接沿用当前解析出
//     的 BaseDir，不重新问、不重新写文件——避免覆盖用户已经调好的设置，见 §10.4
//     「任一级已有 config.yaml 就维持现状」这条规则的 CLI 等价物。
//   - 为 true：真正的全新安装，需要选一个数据目录并写回 basedir 字段。
func resolveSetupBaseDir(flagBaseDir string, nonInteractive bool) (string, error) {
	if !appconfig.WasConfigAutoGenerated() {
		fmt.Printf("检测到已有配置，沿用当前数据目录: %s\n", cfgpkg.BaseDir)
		return cfgpkg.BaseDir, nil
	}

	chosen := flagBaseDir
	if chosen == "" {
		if nonInteractive {
			return "", fmt.Errorf("非交互模式下必须通过 --basedir 指定数据目录")
		}
		var err error
		chosen, err = promptBaseDir()
		if err != nil {
			return "", err
		}
	}

	for {
		if err := appconfig.ValidateBaseDir(chosen); err != nil {
			if nonInteractive {
				return "", err
			}
			fmt.Println(err)
			var promptErr error
			chosen, promptErr = promptBaseDir()
			if promptErr != nil {
				return "", promptErr
			}
			continue
		}
		break
	}

	if err := appconfig.WriteInitialConfig(chosen); err != nil {
		return "", fmt.Errorf("写入 config.yaml 失败: %w", err)
	}
	baseDir, err := appconfig.Load()
	if err != nil {
		return "", fmt.Errorf("重新加载配置失败: %w", err)
	}
	return baseDir, nil
}

func promptBaseDir() (string, error) {
	reader := bufio.NewReader(os.Stdin)
	fmt.Print("请输入数据目录的绝对路径（ARK 服务端本体 + 存档将保存在这里，建议预留至少 30GB 空间）: ")
	line, err := reader.ReadString('\n')
	if err != nil {
		return "", fmt.Errorf("读取输入失败: %w", err)
	}
	line = strings.TrimSpace(line)
	if line == "" {
		return "", fmt.Errorf("数据目录不能为空")
	}
	return line, nil
}
