package userenv

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// ErrNeedRoot 表示写系统级配置（/etc/profile.d）需要 root。
var ErrNeedRoot = errors.New("userenv: 写入 /etc/profile.d 需要 root 权限")

// profileMarker 是 SetProfileScript 写出的文件第一行。覆盖前核对它：同名文件
// 不是我们写的就不碰——那可能是管理员自己放的脚本。
const profileMarker = "# Managed by asa-server."

var envNameRe = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

// profileDir 是 SetProfileScript 的目标目录，单测里替换。
var profileDir = "/etc/profile.d"

// shellQuote 把值包成 POSIX shell 单引号字符串：单引号内一切按字面，唯一要处理的
// 是单引号本身——先闭合引号，再写一个转义的单引号，再重新打开引号。
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// renderProfileScript 生成 /etc/profile.d 片段的内容。
func renderProfileScript(name, value string) (string, error) {
	if !envNameRe.MatchString(name) {
		return "", fmt.Errorf("userenv: 非法的环境变量名 %q", name)
	}
	if strings.ContainsAny(value, "\n\r\x00") {
		return "", fmt.Errorf("userenv: 环境变量 %s 的值不能含换行", name)
	}
	return profileMarker + "\n" +
		"# 由 asa-server 生成；修改请重新运行生成它的命令，删除本文件即取消该环境变量。\n" +
		"# Generated by asa-server; rerun the command that created it to change it, delete this file to unset.\n" +
		"export " + name + "=" + shellQuote(value) + "\n", nil
}

// writeProfileScriptIn 把片段原子写进 dir/file（0644）。同名文件存在但不是本程序
// 写的（首行不是 profileMarker）时拒绝覆盖。
func writeProfileScriptIn(dir, file, name, value string) (string, error) {
	if file == "" || file != filepath.Base(file) || !strings.HasSuffix(file, ".sh") {
		return "", fmt.Errorf("userenv: 非法的 profile.d 文件名 %q（必须是 *.sh 且不含路径）", file)
	}
	content, err := renderProfileScript(name, value)
	if err != nil {
		return "", err
	}
	path := filepath.Join(dir, file)
	if raw, err := os.ReadFile(path); err == nil {
		if !strings.HasPrefix(string(raw), profileMarker) {
			return "", fmt.Errorf("userenv: %s 已存在且不是 asa-server 生成的，不会覆盖；请手动处理", path)
		}
	} else if !errors.Is(err, os.ErrNotExist) {
		return "", fmt.Errorf("userenv: 读取 %s 失败: %w", path, err)
	}

	tmp, err := os.CreateTemp(dir, "."+file+".tmp-*")
	if err != nil {
		return "", fmt.Errorf("userenv: 写入 %s 失败: %w", dir, err)
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName) // rename 成功后是无害的 ENOENT
	if _, err := tmp.WriteString(content); err != nil {
		tmp.Close()
		return "", err
	}
	if err := tmp.Close(); err != nil {
		return "", err
	}
	// /etc/profile.d 里的片段由每个登录 shell source，必须所有人可读。
	if err := os.Chmod(tmpName, 0o644); err != nil {
		return "", err
	}
	if err := os.Rename(tmpName, path); err != nil {
		return "", fmt.Errorf("userenv: 写入 %s 失败: %w", path, err)
	}
	return path, nil
}
