# FRP Client Configuration
# Generated automatically if not present
serverAddr = "47.97.22.91"
auth.token = "9d4d40ad-0ee5-4414-b38d-4e9e787830a1"

{{- range $_, $v := parseNumberRangePair "9310-9319" "9310-9319" }}
[[proxies]]
name = "udp-asaserver-{{ $v.First }}"
type = "udp"
localPort = {{ $v.First }}
remotePort = {{ $v.Second }}
{{- end }}
