// 首次启动向导共用逻辑：Windows Fyne 首次启动对话框与 Linux `asa-server setup`
// CLI 都调这里的函数，不各写一份。见 docs/LINUX_COMPATIBILITY_PLAN.md §10.4/§10.5 G3/G4。
package appconfig

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"asa-server/pkg/fsutil"
)

// minFreeBytesForNewInstall 是 §10.4 规则 1 的硬性下限：ARK 本体约 25GB，
// 加上存档增长，向导要求新建安装至少预留 30GB。
const minFreeBytesForNewInstall = 30 * 1024 * 1024 * 1024

// ValidateBaseDir 校验用户在首次启动向导里选的数据目录，§10.4 的两条硬性规则：
//  1. 可写 + 剩余空间 ≥ 30GB；目录下已存在 config.yaml 时视为"接管已有安装"而不是
//     新建，跳过空间要求——那多半是老部署，数据已经在那儿了，不该被新建的空间
//     下限拦住。
//  2. 不能是映射网络盘/网络文件系统：BadgerDB 用 mmap + 文件锁
//     （{BaseDir}/database_file/state_db），在 SMB/CIFS/NFS 上不可靠，可能直接
//     损坏实例状态库。
//
// 校验失败时的错误信息本身就是给最终用户看的提示文案（Fyne 对话框/CLI 直接原样
// 展示），不是内部诊断信息，因此不用 %w 包裹底层错误、措辞刻意写成"换一个目录"
// 这样可执行的建议，而不是笼统的"校验失败"。
func ValidateBaseDir(dir string) error {
	if isNetwork, err := fsutil.IsNetworkDrive(dir); err == nil && isNetwork {
		return fmt.Errorf("不能选择映射网络盘或网络文件系统目录：%s\n"+
			"BadgerDB 依赖本地文件锁，在网络存储上可能损坏实例状态库，请换一个本地磁盘目录", dir)
	}

	if err := os.MkdirAll(dir, 0o755); err != nil {
		return fmt.Errorf("目录不可写：%s（%v），请换一个有写权限的本地磁盘目录", dir, err)
	}
	probe := filepath.Join(dir, ".asa-server-write-test")
	if err := os.WriteFile(probe, []byte("ok"), 0o644); err != nil {
		return fmt.Errorf("目录不可写：%s（%v），请换一个有写权限的本地磁盘目录", dir, err)
	}
	_ = os.Remove(probe)

	adoptingExisting := fileExists(filepath.Join(dir, ConfigFileName))
	if !adoptingExisting {
		free, err := fsutil.FreeBytes(dir)
		if err != nil {
			return fmt.Errorf("无法读取磁盘剩余空间：%s（%v）", dir, err)
		}
		if free < minFreeBytesForNewInstall {
			return fmt.Errorf("剩余空间不足：ARK 服务端本体约 25GB，建议至少预留 30GB，"+
				"%s 当前仅剩 %.1f GB，请换一个空间更充足的本地磁盘目录", dir, float64(free)/(1<<30))
		}
	}
	return nil
}

// basedirPlaceholder 是 template.go 里默认模板的 basedir 字段行——G1 自动生成的
// config.yaml 里这一行恒为空，WriteInitialConfig 靠精确匹配这一行原地改写，
// 保留模板里给用户看的其余注释。
const basedirPlaceholder = `basedir: ""`

// WriteInitialConfig 把首次启动向导里用户选定的数据目录写回 config.yaml 的
// basedir 字段。
//
// 目标文件固定是"可执行文件同级目录"（§10.3 两级查找的第 2 级）下那份 —— 只有在
// WasConfigAutoGenerated() 为 true（本次 Load 刚生成了默认模板）时才应该调用这个
// 函数，此时那份文件必然存在且 basedir 字段必然是空字符串，因此直接找
// basedirPlaceholder 做原地字符串替换，而不是重新序列化一份新文件：这样能保留
// 模板里给用户手改用的大段注释，重新序列化会把注释全部丢光。
//
// 字段不是预期的空字符串（比如函数被错误地调用在一份已经配置过的文件上）时返回
// 错误、不做任何改写，避免把用户已有的设置悄悄覆盖掉。
func WriteInitialConfig(baseDir string) error {
	exeDir, err := executableDir()
	if err != nil {
		return fmt.Errorf("解析可执行文件目录失败: %w", err)
	}
	path := filepath.Join(exeDir, ConfigFileName)

	raw, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("读取 %s 失败: %w", ConfigFileName, err)
	}
	content := string(raw)
	if !strings.Contains(content, basedirPlaceholder) {
		return fmt.Errorf("%s 的 basedir 字段已被设置或文件格式不是预期的默认模板，"+
			"为避免覆盖已有配置，不会自动改写，请手动编辑该文件", path)
	}
	// strconv.Quote 的转义规则（反斜杠、双引号）和 YAML 双引号标量的转义规则在这里
	// 用得到的字符集上是重合的，BaseDir 路径不会出现两者不一致的边界情况。
	updated := strings.Replace(content, basedirPlaceholder, "basedir: "+strconv.Quote(baseDir), 1)
	if err := os.WriteFile(path, []byte(updated), 0o644); err != nil {
		return fmt.Errorf("写入 %s 失败: %w", path, err)
	}
	return nil
}
