// 管理器 ↔ 协调节点。见 docs/REMOTE_MANAGER_MESH_PLAN.md §5.2、§5.4、§12 P1-1。
//
// 协调节点只做三件事：在线登记、交换候选地址、字节中转。它不理解业务，
// 也不签发任何身份——节点 ID 由管理器自己的公钥决定，协调节点按 TLS 客户端证书算出。
//
// 兼容规则：本服务只做向后兼容的增量（加字段、加方法、加 oneof 分支），字段号永不复用。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: asamesh/v1/coordinator.proto

package meshpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Coordinator_Session_FullMethodName   = "/asamesh.v1.Coordinator/Session"
	Coordinator_Resolve_FullMethodName   = "/asamesh.v1.Coordinator/Resolve"
	Coordinator_OpenRelay_FullMethodName = "/asamesh.v1.Coordinator/OpenRelay"
	Coordinator_Relay_FullMethodName     = "/asamesh.v1.Coordinator/Relay"
)

// CoordinatorClient is the client API for Coordinator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordinatorClient interface {
	// 一条长连接：登记在线、上报候选地址、接收信令（有人要经中转连你、被踢下线）。
	// 首帧必须是 Register；被拒绝时以 PermissionDenied 结束。
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeMessage, CoordMessage], error)
	// 查询同一网络里的某个节点。节点不存在、不在同一网络、不在线一律返回 NotFound。
	Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error)
	// 申请一个中转会话：协调节点经对端的 Session 下发 IncomingRelay，返回本端的会话凭据。
	OpenRelay(ctx context.Context, in *OpenRelayRequest, opts ...grpc.CallOption) (*OpenRelayResponse, error)
	// 中转字节流：首帧 join，之后全是不透明的 data。
	Relay(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RelayFrame, RelayFrame], error)
}

type coordinatorClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorClient(cc grpc.ClientConnInterface) CoordinatorClient {
	return &coordinatorClient{cc}
}

func (c *coordinatorClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NodeMessage, CoordMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Coordinator_ServiceDesc.Streams[0], Coordinator_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NodeMessage, CoordMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Coordinator_SessionClient = grpc.BidiStreamingClient[NodeMessage, CoordMessage]

func (c *coordinatorClient) Resolve(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveResponse)
	err := c.cc.Invoke(ctx, Coordinator_Resolve_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) OpenRelay(ctx context.Context, in *OpenRelayRequest, opts ...grpc.CallOption) (*OpenRelayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OpenRelayResponse)
	err := c.cc.Invoke(ctx, Coordinator_OpenRelay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorClient) Relay(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RelayFrame, RelayFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Coordinator_ServiceDesc.Streams[1], Coordinator_Relay_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RelayFrame, RelayFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Coordinator_RelayClient = grpc.BidiStreamingClient[RelayFrame, RelayFrame]

// CoordinatorServer is the server API for Coordinator service.
// All implementations must embed UnimplementedCoordinatorServer
// for forward compatibility.
type CoordinatorServer interface {
	// 一条长连接：登记在线、上报候选地址、接收信令（有人要经中转连你、被踢下线）。
	// 首帧必须是 Register；被拒绝时以 PermissionDenied 结束。
	Session(grpc.BidiStreamingServer[NodeMessage, CoordMessage]) error
	// 查询同一网络里的某个节点。节点不存在、不在同一网络、不在线一律返回 NotFound。
	Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error)
	// 申请一个中转会话：协调节点经对端的 Session 下发 IncomingRelay，返回本端的会话凭据。
	OpenRelay(context.Context, *OpenRelayRequest) (*OpenRelayResponse, error)
	// 中转字节流：首帧 join，之后全是不透明的 data。
	Relay(grpc.BidiStreamingServer[RelayFrame, RelayFrame]) error
	mustEmbedUnimplementedCoordinatorServer()
}

// UnimplementedCoordinatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinatorServer struct{}

func (UnimplementedCoordinatorServer) Session(grpc.BidiStreamingServer[NodeMessage, CoordMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedCoordinatorServer) Resolve(context.Context, *ResolveRequest) (*ResolveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resolve not implemented")
}
func (UnimplementedCoordinatorServer) OpenRelay(context.Context, *OpenRelayRequest) (*OpenRelayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OpenRelay not implemented")
}
func (UnimplementedCoordinatorServer) Relay(grpc.BidiStreamingServer[RelayFrame, RelayFrame]) error {
	return status.Errorf(codes.Unimplemented, "method Relay not implemented")
}
func (UnimplementedCoordinatorServer) mustEmbedUnimplementedCoordinatorServer() {}
func (UnimplementedCoordinatorServer) testEmbeddedByValue()                     {}

// UnsafeCoordinatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorServer will
// result in compilation errors.
type UnsafeCoordinatorServer interface {
	mustEmbedUnimplementedCoordinatorServer()
}

func RegisterCoordinatorServer(s grpc.ServiceRegistrar, srv CoordinatorServer) {
	// If the following call pancis, it indicates UnimplementedCoordinatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Coordinator_ServiceDesc, srv)
}

func _Coordinator_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CoordinatorServer).Session(&grpc.GenericServerStream[NodeMessage, CoordMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Coordinator_SessionServer = grpc.BidiStreamingServer[NodeMessage, CoordMessage]

func _Coordinator_Resolve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).Resolve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_Resolve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).Resolve(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_OpenRelay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OpenRelayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServer).OpenRelay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coordinator_OpenRelay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServer).OpenRelay(ctx, req.(*OpenRelayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coordinator_Relay_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CoordinatorServer).Relay(&grpc.GenericServerStream[RelayFrame, RelayFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Coordinator_RelayServer = grpc.BidiStreamingServer[RelayFrame, RelayFrame]

// Coordinator_ServiceDesc is the grpc.ServiceDesc for Coordinator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Coordinator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "asamesh.v1.Coordinator",
	HandlerType: (*CoordinatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Resolve",
			Handler:    _Coordinator_Resolve_Handler,
		},
		{
			MethodName: "OpenRelay",
			Handler:    _Coordinator_OpenRelay_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _Coordinator_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Relay",
			Handler:       _Coordinator_Relay_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "asamesh/v1/coordinator.proto",
}
