// 管理器 ↔ 协调节点。见 docs/REMOTE_MANAGER_MESH_PLAN.md §5.2、§5.4、§12 P1-1。
//
// 协调节点只做三件事：在线登记、交换候选地址、字节中转。它不理解业务，
// 也不签发任何身份——节点 ID 由管理器自己的公钥决定，协调节点按 TLS 客户端证书算出。
//
// 兼容规则：本服务只做向后兼容的增量（加字段、加方法、加 oneof 分支），字段号永不复用。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: asamesh/v1/coordinator.proto

package meshpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transport int32

const (
	Transport_TRANSPORT_UNSPECIFIED Transport = 0
	Transport_TRANSPORT_TCP         Transport = 1
	Transport_TRANSPORT_UDP         Transport = 2
)

// Enum value maps for Transport.
var (
	Transport_name = map[int32]string{
		0: "TRANSPORT_UNSPECIFIED",
		1: "TRANSPORT_TCP",
		2: "TRANSPORT_UDP",
	}
	Transport_value = map[string]int32{
		"TRANSPORT_UNSPECIFIED": 0,
		"TRANSPORT_TCP":         1,
		"TRANSPORT_UDP":         2,
	}
)

func (x Transport) Enum() *Transport {
	p := new(Transport)
	*p = x
	return p
}

func (x Transport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Transport) Descriptor() protoreflect.EnumDescriptor {
	return file_asamesh_v1_coordinator_proto_enumTypes[0].Descriptor()
}

func (Transport) Type() protoreflect.EnumType {
	return &file_asamesh_v1_coordinator_proto_enumTypes[0]
}

func (x Transport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Transport.Descriptor instead.
func (Transport) EnumDescriptor() ([]byte, []int) {
	return file_asamesh_v1_coordinator_proto_rawDescGZIP(), []int{0}
}

type CandidateKind int32

const (
	CandidateKind_CANDIDATE_KIND_UNSPECIFIED CandidateKind = 0
	CandidateKind_CANDIDATE_KIND_HOST        CandidateKind = 1 // 本机网卡地址
	CandidateKind_CANDIDATE_KIND_SRFLX       CandidateKind = 2 // STUN 问到的服务器反射地址（P6）
	CandidateKind_CANDIDATE_KIND_MAPPED      CandidateKind = 3 // UPnP / NAT-PMP / PCP 端口映射（P6）
	CandidateKind_CANDIDATE_KIND_CONFIGURED  CandidateKind = 4 // 用户手填的地址
)

// Enum value maps for CandidateKind.
var (
	CandidateKind_name = map[int32]string{
		0: "CANDIDATE_KIND_UNSPECIFIED",
		1: "CANDIDATE_KIND_HOST",
		2: "CANDIDATE_KIND_SRFLX",
		3: "CANDIDATE_KIND_MAPPED",
		4: "CANDIDATE_KIND_CONFIGURED",
	}
	CandidateKind_value = map[string]int32{
		"CANDIDATE_KIND_UNSPECIFIED": 0,
		"CANDIDATE_KIND_HOST":        1,
		"CANDIDATE_KIND_SRFLX":       2,
		"CANDIDATE_KIND_MAPPED":      3,
		"CANDIDATE_KIND_CONFIGURED":  4,
	}
)

func (x CandidateKind) Enum() *CandidateKind {
	p := new(CandidateKind)
	*p = x
	return p
}

func (x CandidateKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CandidateKind) Descriptor() protoreflect.EnumDescriptor {
	return file_asamesh_v1_coordinator_proto_enumTypes[1].Descriptor()
}

func (CandidateKind) Type() protoreflect.EnumType {
	return &file_asamesh_v1_coordinator_proto_enumTypes[1]
}

func (x CandidateKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CandidateKind.Descriptor instead.
func (CandidateKind) EnumDescriptor() ([]byte, []int) {
	return file_asamesh_v1_coordinator_proto_rawDescGZIP(), []int{1}
}

type Candidate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transport     Transport              `protobuf:"varint,1,opt,name=transport,proto3,enum=asamesh.v1.Transport" json:"transport,omitempty"`
	Kind          CandidateKind          `protobuf:"varint,2,opt,name=kind,proto3,enum=asamesh.v1.CandidateKind" json:"kind,omitempty"`
	Addr          string                 `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"` // host:port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candidate) Reset() {
	*x = Candidate{}
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candidate) ProtoMessage() {}

func (x *Candidate) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candidate.ProtoReflect.Descriptor instead.
func (*Candidate) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_coordinator_proto_rawDescGZIP(), []int{0}
}

func (x *Candidate) GetTransport() Transport {
	if x != nil {
		return x.Transport
	}
	return Transport_TRANSPORT_UNSPECIFIED
}

func (x *Candidate) GetKind() CandidateKind {
	if x != nil {
		return x.Kind
	}
	return CandidateKind_CANDIDATE_KIND_UNSPECIFIED
}

func (x *Candidate) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

type NodeMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*NodeMessage_Register
	//	*NodeMessage_Candidates
	//	*NodeMessage_PunchOffer
	//	*NodeMessage_PunchAnswer
	Msg           isNodeMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeMessage) Reset() {
	*x = NodeMessage{}
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMessage) ProtoMessage() {}

func (x *NodeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMessage.ProtoReflect.Descriptor instead.
func (*NodeMessage) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_coordinator_proto_rawDescGZIP(), []int{1}
}

func (x *NodeMessage) GetMsg() isNodeMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *NodeMessage) GetRegister() *Register {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *NodeMessage) GetCandidates() *CandidatesUpdate {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_Candidates); ok {
			return x.Candidates
		}
	}
	return nil
}

func (x *NodeMessage) GetPunchOffer() *PunchOffer {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_PunchOffer); ok {
			return x.PunchOffer
		}
	}
	return nil
}

func (x *NodeMessage) GetPunchAnswer() *PunchAnswer {
	if x != nil {
		if x, ok := x.Msg.(*NodeMessage_PunchAnswer); ok {
			return x.PunchAnswer
		}
	}
	return nil
}

type isNodeMessage_Msg interface {
	isNodeMessage_Msg()
}

type NodeMessage_Register struct {
	Register *Register `protobuf:"bytes,1,opt,name=register,proto3,oneof"` // Session 首帧，且只能是首帧
}

type NodeMessage_Candidates struct {
	Candidates *CandidatesUpdate `protobuf:"bytes,2,opt,name=candidates,proto3,oneof"` // P2
}

type NodeMessage_PunchOffer struct {
	PunchOffer *PunchOffer `protobuf:"bytes,10,opt,name=punch_offer,json=punchOffer,proto3,oneof"` // P6（§5.6），P1 只定义不实现
}

type NodeMessage_PunchAnswer struct {
	PunchAnswer *PunchAnswer `protobuf:"bytes,11,opt,name=punch_answer,json=punchAnswer,proto3,oneof"` // P6
}

func (*NodeMessage_Register) isNodeMessage_Msg() {}

func (*NodeMessage_Candidates) isNodeMessage_Msg() {}

func (*NodeMessage_PunchOffer) isNodeMessage_Msg() {}

func (*NodeMessage_PunchAnswer) isNodeMessage_Msg() {}

type Register struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	NetworkId string                 `protobuf:"bytes,1,opt,name=network_id,json=networkId,proto3" json:"network_id,omitempty"`
	// 只在首次接入时必需；已是该网络成员时协调节点忽略它。
	NetworkSecret string `protobuf:"bytes,2,opt,name=network_secret,json=networkSecret,proto3" json:"network_secret,omitempty"`
	Version       string `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	// P1 声明 "relay.v1"；打洞是 "punch.v1"。
	Capabilities []string     `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Candidates   []*Candidate `protobuf:"bytes,5,rep,name=candidates,proto3" json:"candidates,omitempty"`
	// 本机备注名，只给协调节点的 node list 看。
	Label         string `protobuf:"bytes,6,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Register) Reset() {
	*x = Register{}
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_coordinator_proto_rawDescGZIP(), []int{2}
}

func (x *Register) GetNetworkId() string {
	if x != nil {
		return x.NetworkId
	}
	return ""
}

func (x *Register) GetNetworkSecret() string {
	if x != nil {
		return x.NetworkSecret
	}
	return ""
}

func (x *Register) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Register) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Register) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *Register) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type CandidatesUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidates    []*Candidate           `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandidatesUpdate) Reset() {
	*x = CandidatesUpdate{}
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandidatesUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandidatesUpdate) ProtoMessage() {}

func (x *CandidatesUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandidatesUpdate.ProtoReflect.Descriptor instead.
func (*CandidatesUpdate) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_coordinator_proto_rawDescGZIP(), []int{3}
}

func (x *CandidatesUpdate) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type CoordMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*CoordMessage_Registered
	//	*CoordMessage_IncomingRelay
	//	*CoordMessage_Kicked
	//	*CoordMessage_PunchStart
	Msg           isCoordMessage_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoordMessage) Reset() {
	*x = CoordMessage{}
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordMessage) ProtoMessage() {}

func (x *CoordMessage) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordMessage.ProtoReflect.Descriptor instead.
func (*CoordMessage) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_coordinator_proto_rawDescGZIP(), []int{4}
}

func (x *CoordMessage) GetMsg() isCoordMessage_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *CoordMessage) GetRegistered() *Registered {
	if x != nil {
		if x, ok := x.Msg.(*CoordMessage_Registered); ok {
			return x.Registered
		}
	}
	return nil
}

func (x *CoordMessage) GetIncomingRelay() *IncomingRelay {
	if x != nil {
		if x, ok := x.Msg.(*CoordMessage_IncomingRelay); ok {
			return x.IncomingRelay
		}
	}
	return nil
}

func (x *CoordMessage) GetKicked() *Kicked {
	if x != nil {
		if x, ok := x.Msg.(*CoordMessage_Kicked); ok {
			return x.Kicked
		}
	}
	return nil
}

func (x *CoordMessage) GetPunchStart() *PunchStart {
	if x != nil {
		if x, ok := x.Msg.(*CoordMessage_PunchStart); ok {
			return x.PunchStart
		}
	}
	return nil
}

type isCoordMessage_Msg interface {
	isCoordMessage_Msg()
}

type CoordMessage_Registered struct {
	Registered *Registered `protobuf:"bytes,1,opt,name=registered,proto3,oneof"`
}

type CoordMessage_IncomingRelay struct {
	IncomingRelay *IncomingRelay `protobuf:"bytes,2,opt,name=incoming_relay,json=incomingRelay,proto3,oneof"`
}

type CoordMessage_Kicked struct {
	Kicked *Kicked `protobuf:"bytes,3,opt,name=kicked,proto3,oneof"`
}

type CoordMessage_PunchStart struct {
	PunchStart *PunchStart `protobuf:"bytes,10,opt,name=punch_start,json=punchStart,proto3,oneof"` // P6
}

func (*CoordMessage_Registered) isCoordMessage_Msg() {}

func (*CoordMessage_IncomingRelay) isCoordMessage_Msg() {}

func (*CoordMessage_Kicked) isCoordMessage_Msg() {}

func (*CoordMessage_PunchStart) isCoordMessage_Msg() {}

type Registered struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 协调节点按 TLS 客户端证书算出的节点 ID，回显给管理器核对。
	NodeId string `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// 协调节点看到的本端出口地址（ip:port）。
	ObservedAddr     string `protobuf:"bytes,2,opt,name=observed_addr,json=observedAddr,proto3" json:"observed_addr,omitempty"`
	ServerTimeUnixMs int64  `protobuf:"varint,3,opt,name=server_time_unix_ms,json=serverTimeUnixMs,proto3" json:"server_time_unix_ms,omitempty"`
	// 协调节点的 STUN 地址（host:port，主机名由管理器自己解析）；未开 STUN 时为空。
	StunAddrs     []string `protobuf:"bytes,4,rep,name=stun_addrs,json=stunAddrs,proto3" json:"stun_addrs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Registered) Reset() {
	*x = Registered{}
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Registered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Registered) ProtoMessage() {}

func (x *Registered) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Registered.ProtoReflect.Descriptor instead.
func (*Registered) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_coordinator_proto_rawDescGZIP(), []int{5}
}

func (x *Registered) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Registered) GetObservedAddr() string {
	if x != nil {
		return x.ObservedAddr
	}
	return ""
}

func (x *Registered) GetServerTimeUnixMs() int64 {
	if x != nil {
		return x.ServerTimeUnixMs
	}
	return 0
}

func (x *Registered) GetStunAddrs() []string {
	if x != nil {
		return x.StunAddrs
	}
	return nil
}

type IncomingRelay struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromNodeId    string                 `protobuf:"bytes,2,opt,name=from_node_id,json=fromNodeId,proto3" json:"from_node_id,omitempty"`
	Token         []byte                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncomingRelay) Reset() {
	*x = IncomingRelay{}
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomingRelay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomingRelay) ProtoMessage() {}

func (x *IncomingRelay) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomingRelay.ProtoReflect.Descriptor instead.
func (*IncomingRelay) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_coordinator_proto_rawDescGZIP(), []int{6}
}

func (x *IncomingRelay) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *IncomingRelay) GetFromNodeId() string {
	if x != nil {
		return x.FromNodeId
	}
	return ""
}

func (x *IncomingRelay) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type Kicked struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Kicked) Reset() {
	*x = Kicked{}
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Kicked) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kicked) ProtoMessage() {}

func (x *Kicked) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kicked.ProtoReflect.Descriptor instead.
func (*Kicked) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_coordinator_proto_rawDescGZIP(), []int{7}
}

func (x *Kicked) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PunchOffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetNodeId  string                 `protobuf:"bytes,1,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Candidates    []*Candidate           `protobuf:"bytes,3,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PunchOffer) Reset() {
	*x = PunchOffer{}
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PunchOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PunchOffer) ProtoMessage() {}

func (x *PunchOffer) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PunchOffer.ProtoReflect.Descriptor instead.
func (*PunchOffer) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_coordinator_proto_rawDescGZIP(), []int{8}
}

func (x *PunchOffer) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

func (x *PunchOffer) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PunchOffer) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type PunchAnswer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Candidates    []*Candidate           `protobuf:"bytes,2,rep,name=candidates,proto3" json:"candidates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PunchAnswer) Reset() {
	*x = PunchAnswer{}
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PunchAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PunchAnswer) ProtoMessage() {}

func (x *PunchAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PunchAnswer.ProtoReflect.Descriptor instead.
func (*PunchAnswer) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_coordinator_proto_rawDescGZIP(), []int{9}
}

func (x *PunchAnswer) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PunchAnswer) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

type PunchStart struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SessionId      string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PeerNodeId     string                 `protobuf:"bytes,2,opt,name=peer_node_id,json=peerNodeId,proto3" json:"peer_node_id,omitempty"`
	PeerCandidates []*Candidate           `protobuf:"bytes,3,rep,name=peer_candidates,json=peerCandidates,proto3" json:"peer_candidates,omitempty"`
	StartUnixMs    int64                  `protobuf:"varint,4,opt,name=start_unix_ms,json=startUnixMs,proto3" json:"start_unix_ms,omitempty"`
	SessionKey     []byte                 `protobuf:"bytes,5,opt,name=session_key,json=sessionKey,proto3" json:"session_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PunchStart) Reset() {
	*x = PunchStart{}
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PunchStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PunchStart) ProtoMessage() {}

func (x *PunchStart) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PunchStart.ProtoReflect.Descriptor instead.
func (*PunchStart) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_coordinator_proto_rawDescGZIP(), []int{10}
}

func (x *PunchStart) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PunchStart) GetPeerNodeId() string {
	if x != nil {
		return x.PeerNodeId
	}
	return ""
}

func (x *PunchStart) GetPeerCandidates() []*Candidate {
	if x != nil {
		return x.PeerCandidates
	}
	return nil
}

func (x *PunchStart) GetStartUnixMs() int64 {
	if x != nil {
		return x.StartUnixMs
	}
	return 0
}

func (x *PunchStart) GetSessionKey() []byte {
	if x != nil {
		return x.SessionKey
	}
	return nil
}

// ⚠️ 没有 network_id 字段——网络只能来自调用者自己的 Session（§8.4.5）。
type ResolveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_coordinator_proto_rawDescGZIP(), []int{11}
}

func (x *ResolveRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ResolveResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Version        string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities   []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	Candidates     []*Candidate           `protobuf:"bytes,3,rep,name=candidates,proto3" json:"candidates,omitempty"`
	PeerObservedIp string                 `protobuf:"bytes,4,opt,name=peer_observed_ip,json=peerObservedIp,proto3" json:"peer_observed_ip,omitempty"`
	SelfObservedIp string                 `protobuf:"bytes,5,opt,name=self_observed_ip,json=selfObservedIp,proto3" json:"self_observed_ip,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_coordinator_proto_rawDescGZIP(), []int{12}
}

func (x *ResolveResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ResolveResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *ResolveResponse) GetCandidates() []*Candidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *ResolveResponse) GetPeerObservedIp() string {
	if x != nil {
		return x.PeerObservedIp
	}
	return ""
}

func (x *ResolveResponse) GetSelfObservedIp() string {
	if x != nil {
		return x.SelfObservedIp
	}
	return ""
}

type OpenRelayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetNodeId  string                 `protobuf:"bytes,1,opt,name=target_node_id,json=targetNodeId,proto3" json:"target_node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRelayRequest) Reset() {
	*x = OpenRelayRequest{}
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRelayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRelayRequest) ProtoMessage() {}

func (x *OpenRelayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRelayRequest.ProtoReflect.Descriptor instead.
func (*OpenRelayRequest) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_coordinator_proto_rawDescGZIP(), []int{13}
}

func (x *OpenRelayRequest) GetTargetNodeId() string {
	if x != nil {
		return x.TargetNodeId
	}
	return ""
}

type OpenRelayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Token         []byte                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRelayResponse) Reset() {
	*x = OpenRelayResponse{}
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRelayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRelayResponse) ProtoMessage() {}

func (x *OpenRelayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRelayResponse.ProtoReflect.Descriptor instead.
func (*OpenRelayResponse) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_coordinator_proto_rawDescGZIP(), []int{14}
}

func (x *OpenRelayResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *OpenRelayResponse) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

type RelayFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*RelayFrame_Join
	//	*RelayFrame_Data
	Msg           isRelayFrame_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayFrame) Reset() {
	*x = RelayFrame{}
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayFrame) ProtoMessage() {}

func (x *RelayFrame) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayFrame.ProtoReflect.Descriptor instead.
func (*RelayFrame) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_coordinator_proto_rawDescGZIP(), []int{15}
}

func (x *RelayFrame) GetMsg() isRelayFrame_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *RelayFrame) GetJoin() *RelayJoin {
	if x != nil {
		if x, ok := x.Msg.(*RelayFrame_Join); ok {
			return x.Join
		}
	}
	return nil
}

func (x *RelayFrame) GetData() []byte {
	if x != nil {
		if x, ok := x.Msg.(*RelayFrame_Data); ok {
			return x.Data
		}
	}
	return nil
}

type isRelayFrame_Msg interface {
	isRelayFrame_Msg()
}

type RelayFrame_Join struct {
	Join *RelayJoin `protobuf:"bytes,1,opt,name=join,proto3,oneof"`
}

type RelayFrame_Data struct {
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*RelayFrame_Join) isRelayFrame_Msg() {}

func (*RelayFrame_Data) isRelayFrame_Msg() {}

type RelayJoin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Token         []byte                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayJoin) Reset() {
	*x = RelayJoin{}
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayJoin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayJoin) ProtoMessage() {}

func (x *RelayJoin) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_coordinator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayJoin.ProtoReflect.Descriptor instead.
func (*RelayJoin) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_coordinator_proto_rawDescGZIP(), []int{16}
}

func (x *RelayJoin) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RelayJoin) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

var File_asamesh_v1_coordinator_proto protoreflect.FileDescriptor

const file_asamesh_v1_coordinator_proto_rawDesc = "" +
	"\n" +
	"\x1casamesh/v1/coordinator.proto\x12\n" +
	"asamesh.v1\"\x83\x01\n" +
	"\tCandidate\x123\n" +
	"\ttransport\x18\x01 \x01(\x0e2\x15.asamesh.v1.TransportR\ttransport\x12-\n" +
	"\x04kind\x18\x02 \x01(\x0e2\x19.asamesh.v1.CandidateKindR\x04kind\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\tR\x04addr\"\x81\x02\n" +
	"\vNodeMessage\x122\n" +
	"\bregister\x18\x01 \x01(\v2\x14.asamesh.v1.RegisterH\x00R\bregister\x12>\n" +
	"\n" +
	"candidates\x18\x02 \x01(\v2\x1c.asamesh.v1.CandidatesUpdateH\x00R\n" +
	"candidates\x129\n" +
	"\vpunch_offer\x18\n" +
	" \x01(\v2\x16.asamesh.v1.PunchOfferH\x00R\n" +
	"punchOffer\x12<\n" +
	"\fpunch_answer\x18\v \x01(\v2\x17.asamesh.v1.PunchAnswerH\x00R\vpunchAnswerB\x05\n" +
	"\x03msg\"\xdb\x01\n" +
	"\bRegister\x12\x1d\n" +
	"\n" +
	"network_id\x18\x01 \x01(\tR\tnetworkId\x12%\n" +
	"\x0enetwork_secret\x18\x02 \x01(\tR\rnetworkSecret\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\x125\n" +
	"\n" +
	"candidates\x18\x05 \x03(\v2\x15.asamesh.v1.CandidateR\n" +
	"candidates\x12\x14\n" +
	"\x05label\x18\x06 \x01(\tR\x05label\"I\n" +
	"\x10CandidatesUpdate\x125\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2\x15.asamesh.v1.CandidateR\n" +
	"candidates\"\xfc\x01\n" +
	"\fCoordMessage\x128\n" +
	"\n" +
	"registered\x18\x01 \x01(\v2\x16.asamesh.v1.RegisteredH\x00R\n" +
	"registered\x12B\n" +
	"\x0eincoming_relay\x18\x02 \x01(\v2\x19.asamesh.v1.IncomingRelayH\x00R\rincomingRelay\x12,\n" +
	"\x06kicked\x18\x03 \x01(\v2\x12.asamesh.v1.KickedH\x00R\x06kicked\x129\n" +
	"\vpunch_start\x18\n" +
	" \x01(\v2\x16.asamesh.v1.PunchStartH\x00R\n" +
	"punchStartB\x05\n" +
	"\x03msg\"\x98\x01\n" +
	"\n" +
	"Registered\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12#\n" +
	"\robserved_addr\x18\x02 \x01(\tR\fobservedAddr\x12-\n" +
	"\x13server_time_unix_ms\x18\x03 \x01(\x03R\x10serverTimeUnixMs\x12\x1d\n" +
	"\n" +
	"stun_addrs\x18\x04 \x03(\tR\tstunAddrs\"f\n" +
	"\rIncomingRelay\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12 \n" +
	"\ffrom_node_id\x18\x02 \x01(\tR\n" +
	"fromNodeId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\fR\x05token\" \n" +
	"\x06Kicked\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\x88\x01\n" +
	"\n" +
	"PunchOffer\x12$\n" +
	"\x0etarget_node_id\x18\x01 \x01(\tR\ftargetNodeId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x125\n" +
	"\n" +
	"candidates\x18\x03 \x03(\v2\x15.asamesh.v1.CandidateR\n" +
	"candidates\"c\n" +
	"\vPunchAnswer\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x125\n" +
	"\n" +
	"candidates\x18\x02 \x03(\v2\x15.asamesh.v1.CandidateR\n" +
	"candidates\"\xd2\x01\n" +
	"\n" +
	"PunchStart\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12 \n" +
	"\fpeer_node_id\x18\x02 \x01(\tR\n" +
	"peerNodeId\x12>\n" +
	"\x0fpeer_candidates\x18\x03 \x03(\v2\x15.asamesh.v1.CandidateR\x0epeerCandidates\x12\"\n" +
	"\rstart_unix_ms\x18\x04 \x01(\x03R\vstartUnixMs\x12\x1f\n" +
	"\vsession_key\x18\x05 \x01(\fR\n" +
	"sessionKey\")\n" +
	"\x0eResolveRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"\xda\x01\n" +
	"\x0fResolveResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x125\n" +
	"\n" +
	"candidates\x18\x03 \x03(\v2\x15.asamesh.v1.CandidateR\n" +
	"candidates\x12(\n" +
	"\x10peer_observed_ip\x18\x04 \x01(\tR\x0epeerObservedIp\x12(\n" +
	"\x10self_observed_ip\x18\x05 \x01(\tR\x0eselfObservedIp\"8\n" +
	"\x10OpenRelayRequest\x12$\n" +
	"\x0etarget_node_id\x18\x01 \x01(\tR\ftargetNodeId\"H\n" +
	"\x11OpenRelayResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\fR\x05token\"V\n" +
	"\n" +
	"RelayFrame\x12+\n" +
	"\x04join\x18\x01 \x01(\v2\x15.asamesh.v1.RelayJoinH\x00R\x04join\x12\x14\n" +
	"\x04data\x18\x02 \x01(\fH\x00R\x04dataB\x05\n" +
	"\x03msg\"@\n" +
	"\tRelayJoin\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\fR\x05token*L\n" +
	"\tTransport\x12\x19\n" +
	"\x15TRANSPORT_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rTRANSPORT_TCP\x10\x01\x12\x11\n" +
	"\rTRANSPORT_UDP\x10\x02*\x9c\x01\n" +
	"\rCandidateKind\x12\x1e\n" +
	"\x1aCANDIDATE_KIND_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13CANDIDATE_KIND_HOST\x10\x01\x12\x18\n" +
	"\x14CANDIDATE_KIND_SRFLX\x10\x02\x12\x19\n" +
	"\x15CANDIDATE_KIND_MAPPED\x10\x03\x12\x1d\n" +
	"\x19CANDIDATE_KIND_CONFIGURED\x10\x042\x9a\x02\n" +
	"\vCoordinator\x12@\n" +
	"\aSession\x12\x17.asamesh.v1.NodeMessage\x1a\x18.asamesh.v1.CoordMessage(\x010\x01\x12B\n" +
	"\aResolve\x12\x1a.asamesh.v1.ResolveRequest\x1a\x1b.asamesh.v1.ResolveResponse\x12H\n" +
	"\tOpenRelay\x12\x1c.asamesh.v1.OpenRelayRequest\x1a\x1d.asamesh.v1.OpenRelayResponse\x12;\n" +
	"\x05Relay\x12\x16.asamesh.v1.RelayFrame\x1a\x16.asamesh.v1.RelayFrame(\x010\x01B(Z&asa-server/internal/mesh/meshpb;meshpbb\x06proto3"

var (
	file_asamesh_v1_coordinator_proto_rawDescOnce sync.Once
	file_asamesh_v1_coordinator_proto_rawDescData []byte
)

func file_asamesh_v1_coordinator_proto_rawDescGZIP() []byte {
	file_asamesh_v1_coordinator_proto_rawDescOnce.Do(func() {
		file_asamesh_v1_coordinator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_asamesh_v1_coordinator_proto_rawDesc), len(file_asamesh_v1_coordinator_proto_rawDesc)))
	})
	return file_asamesh_v1_coordinator_proto_rawDescData
}

var file_asamesh_v1_coordinator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_asamesh_v1_coordinator_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_asamesh_v1_coordinator_proto_goTypes = []any{
	(Transport)(0),            // 0: asamesh.v1.Transport
	(CandidateKind)(0),        // 1: asamesh.v1.CandidateKind
	(*Candidate)(nil),         // 2: asamesh.v1.Candidate
	(*NodeMessage)(nil),       // 3: asamesh.v1.NodeMessage
	(*Register)(nil),          // 4: asamesh.v1.Register
	(*CandidatesUpdate)(nil),  // 5: asamesh.v1.CandidatesUpdate
	(*CoordMessage)(nil),      // 6: asamesh.v1.CoordMessage
	(*Registered)(nil),        // 7: asamesh.v1.Registered
	(*IncomingRelay)(nil),     // 8: asamesh.v1.IncomingRelay
	(*Kicked)(nil),            // 9: asamesh.v1.Kicked
	(*PunchOffer)(nil),        // 10: asamesh.v1.PunchOffer
	(*PunchAnswer)(nil),       // 11: asamesh.v1.PunchAnswer
	(*PunchStart)(nil),        // 12: asamesh.v1.PunchStart
	(*ResolveRequest)(nil),    // 13: asamesh.v1.ResolveRequest
	(*ResolveResponse)(nil),   // 14: asamesh.v1.ResolveResponse
	(*OpenRelayRequest)(nil),  // 15: asamesh.v1.OpenRelayRequest
	(*OpenRelayResponse)(nil), // 16: asamesh.v1.OpenRelayResponse
	(*RelayFrame)(nil),        // 17: asamesh.v1.RelayFrame
	(*RelayJoin)(nil),         // 18: asamesh.v1.RelayJoin
}
var file_asamesh_v1_coordinator_proto_depIdxs = []int32{
	0,  // 0: asamesh.v1.Candidate.transport:type_name -> asamesh.v1.Transport
	1,  // 1: asamesh.v1.Candidate.kind:type_name -> asamesh.v1.CandidateKind
	4,  // 2: asamesh.v1.NodeMessage.register:type_name -> asamesh.v1.Register
	5,  // 3: asamesh.v1.NodeMessage.candidates:type_name -> asamesh.v1.CandidatesUpdate
	10, // 4: asamesh.v1.NodeMessage.punch_offer:type_name -> asamesh.v1.PunchOffer
	11, // 5: asamesh.v1.NodeMessage.punch_answer:type_name -> asamesh.v1.PunchAnswer
	2,  // 6: asamesh.v1.Register.candidates:type_name -> asamesh.v1.Candidate
	2,  // 7: asamesh.v1.CandidatesUpdate.candidates:type_name -> asamesh.v1.Candidate
	7,  // 8: asamesh.v1.CoordMessage.registered:type_name -> asamesh.v1.Registered
	8,  // 9: asamesh.v1.CoordMessage.incoming_relay:type_name -> asamesh.v1.IncomingRelay
	9,  // 10: asamesh.v1.CoordMessage.kicked:type_name -> asamesh.v1.Kicked
	12, // 11: asamesh.v1.CoordMessage.punch_start:type_name -> asamesh.v1.PunchStart
	2,  // 12: asamesh.v1.PunchOffer.candidates:type_name -> asamesh.v1.Candidate
	2,  // 13: asamesh.v1.PunchAnswer.candidates:type_name -> asamesh.v1.Candidate
	2,  // 14: asamesh.v1.PunchStart.peer_candidates:type_name -> asamesh.v1.Candidate
	2,  // 15: asamesh.v1.ResolveResponse.candidates:type_name -> asamesh.v1.Candidate
	18, // 16: asamesh.v1.RelayFrame.join:type_name -> asamesh.v1.RelayJoin
	3,  // 17: asamesh.v1.Coordinator.Session:input_type -> asamesh.v1.NodeMessage
	13, // 18: asamesh.v1.Coordinator.Resolve:input_type -> asamesh.v1.ResolveRequest
	15, // 19: asamesh.v1.Coordinator.OpenRelay:input_type -> asamesh.v1.OpenRelayRequest
	17, // 20: asamesh.v1.Coordinator.Relay:input_type -> asamesh.v1.RelayFrame
	6,  // 21: asamesh.v1.Coordinator.Session:output_type -> asamesh.v1.CoordMessage
	14, // 22: asamesh.v1.Coordinator.Resolve:output_type -> asamesh.v1.ResolveResponse
	16, // 23: asamesh.v1.Coordinator.OpenRelay:output_type -> asamesh.v1.OpenRelayResponse
	17, // 24: asamesh.v1.Coordinator.Relay:output_type -> asamesh.v1.RelayFrame
	21, // [21:25] is the sub-list for method output_type
	17, // [17:21] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_asamesh_v1_coordinator_proto_init() }
func file_asamesh_v1_coordinator_proto_init() {
	if File_asamesh_v1_coordinator_proto != nil {
		return
	}
	file_asamesh_v1_coordinator_proto_msgTypes[1].OneofWrappers = []any{
		(*NodeMessage_Register)(nil),
		(*NodeMessage_Candidates)(nil),
		(*NodeMessage_PunchOffer)(nil),
		(*NodeMessage_PunchAnswer)(nil),
	}
	file_asamesh_v1_coordinator_proto_msgTypes[4].OneofWrappers = []any{
		(*CoordMessage_Registered)(nil),
		(*CoordMessage_IncomingRelay)(nil),
		(*CoordMessage_Kicked)(nil),
		(*CoordMessage_PunchStart)(nil),
	}
	file_asamesh_v1_coordinator_proto_msgTypes[15].OneofWrappers = []any{
		(*RelayFrame_Join)(nil),
		(*RelayFrame_Data)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_asamesh_v1_coordinator_proto_rawDesc), len(file_asamesh_v1_coordinator_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_asamesh_v1_coordinator_proto_goTypes,
		DependencyIndexes: file_asamesh_v1_coordinator_proto_depIdxs,
		EnumInfos:         file_asamesh_v1_coordinator_proto_enumTypes,
		MessageInfos:      file_asamesh_v1_coordinator_proto_msgTypes,
	}.Build()
	File_asamesh_v1_coordinator_proto = out.File
	file_asamesh_v1_coordinator_proto_goTypes = nil
	file_asamesh_v1_coordinator_proto_depIdxs = nil
}
