// 管理器 ↔ 管理器。跑在端到端 mTLS 之上（直连或经中转），见
// docs/REMOTE_MANAGER_MESH_PLAN.md §5.5、§12 P1-1。
//
// P1 只有 Hello；Pair 与 HTTP（P3）以后作为新方法追加，加方法不是破坏性变更。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: asamesh/v1/peer.proto

package meshpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_NONE     Role = 0
	Role_ROLE_OPERATOR Role = 1
	Role_ROLE_ADMIN    Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_NONE",
		1: "ROLE_OPERATOR",
		2: "ROLE_ADMIN",
	}
	Role_value = map[string]int32{
		"ROLE_NONE":     0,
		"ROLE_OPERATOR": 1,
		"ROLE_ADMIN":    2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_asamesh_v1_peer_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_asamesh_v1_peer_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_asamesh_v1_peer_proto_rawDescGZIP(), []int{0}
}

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities  []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_asamesh_v1_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_peer_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HelloRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type HelloResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Version      string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// P1 恒为 ROLE_NONE。
	GrantedRole Role `protobuf:"varint,3,opt,name=granted_role,json=grantedRole,proto3,enum=asamesh.v1.Role" json:"granted_role,omitempty"`
	// 只对已配对的身份填写。
	Label         string `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_asamesh_v1_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_peer_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HelloResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *HelloResponse) GetGrantedRole() Role {
	if x != nil {
		return x.GrantedRole
	}
	return Role_ROLE_NONE
}

func (x *HelloResponse) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

var File_asamesh_v1_peer_proto protoreflect.FileDescriptor

const file_asamesh_v1_peer_proto_rawDesc = "" +
	"\n" +
	"\x15asamesh/v1/peer.proto\x12\n" +
	"asamesh.v1\"L\n" +
	"\fHelloRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\"\x98\x01\n" +
	"\rHelloResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x123\n" +
	"\fgranted_role\x18\x03 \x01(\x0e2\x10.asamesh.v1.RoleR\vgrantedRole\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label*8\n" +
	"\x04Role\x12\r\n" +
	"\tROLE_NONE\x10\x00\x12\x11\n" +
	"\rROLE_OPERATOR\x10\x01\x12\x0e\n" +
	"\n" +
	"ROLE_ADMIN\x10\x022D\n" +
	"\x04Peer\x12<\n" +
	"\x05Hello\x12\x18.asamesh.v1.HelloRequest\x1a\x19.asamesh.v1.HelloResponseB(Z&asa-server/internal/mesh/meshpb;meshpbb\x06proto3"

var (
	file_asamesh_v1_peer_proto_rawDescOnce sync.Once
	file_asamesh_v1_peer_proto_rawDescData []byte
)

func file_asamesh_v1_peer_proto_rawDescGZIP() []byte {
	file_asamesh_v1_peer_proto_rawDescOnce.Do(func() {
		file_asamesh_v1_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_asamesh_v1_peer_proto_rawDesc), len(file_asamesh_v1_peer_proto_rawDesc)))
	})
	return file_asamesh_v1_peer_proto_rawDescData
}

var file_asamesh_v1_peer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_asamesh_v1_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_asamesh_v1_peer_proto_goTypes = []any{
	(Role)(0),             // 0: asamesh.v1.Role
	(*HelloRequest)(nil),  // 1: asamesh.v1.HelloRequest
	(*HelloResponse)(nil), // 2: asamesh.v1.HelloResponse
}
var file_asamesh_v1_peer_proto_depIdxs = []int32{
	0, // 0: asamesh.v1.HelloResponse.granted_role:type_name -> asamesh.v1.Role
	1, // 1: asamesh.v1.Peer.Hello:input_type -> asamesh.v1.HelloRequest
	2, // 2: asamesh.v1.Peer.Hello:output_type -> asamesh.v1.HelloResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_asamesh_v1_peer_proto_init() }
func file_asamesh_v1_peer_proto_init() {
	if File_asamesh_v1_peer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_asamesh_v1_peer_proto_rawDesc), len(file_asamesh_v1_peer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_asamesh_v1_peer_proto_goTypes,
		DependencyIndexes: file_asamesh_v1_peer_proto_depIdxs,
		EnumInfos:         file_asamesh_v1_peer_proto_enumTypes,
		MessageInfos:      file_asamesh_v1_peer_proto_msgTypes,
	}.Build()
	File_asamesh_v1_peer_proto = out.File
	file_asamesh_v1_peer_proto_goTypes = nil
	file_asamesh_v1_peer_proto_depIdxs = nil
}
