// 管理器 ↔ 管理器。跑在端到端 mTLS 之上（直连或经中转），见
// docs/REMOTE_MANAGER_MESH_PLAN.md §5.5、§12 P1-1、P3-3、P3-4。
//
// 兼容规则同 coordinator.proto：只做向后兼容的增量，字段号永不复用。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: asamesh/v1/peer.proto

package meshpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_ROLE_NONE     Role = 0
	Role_ROLE_OPERATOR Role = 1
	Role_ROLE_ADMIN    Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_NONE",
		1: "ROLE_OPERATOR",
		2: "ROLE_ADMIN",
	}
	Role_value = map[string]int32{
		"ROLE_NONE":     0,
		"ROLE_OPERATOR": 1,
		"ROLE_ADMIN":    2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_asamesh_v1_peer_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_asamesh_v1_peer_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_asamesh_v1_peer_proto_rawDescGZIP(), []int{0}
}

type PairStatus int32

const (
	PairStatus_PAIR_STATUS_UNSPECIFIED PairStatus = 0
	// 已授权（带有效邀请码，或之前就授权过）。
	PairStatus_PAIR_STATUS_PAIRED PairStatus = 1
	// 已提交申请，等对方的管理员批准。
	PairStatus_PAIR_STATUS_PENDING PairStatus = 2
)

// Enum value maps for PairStatus.
var (
	PairStatus_name = map[int32]string{
		0: "PAIR_STATUS_UNSPECIFIED",
		1: "PAIR_STATUS_PAIRED",
		2: "PAIR_STATUS_PENDING",
	}
	PairStatus_value = map[string]int32{
		"PAIR_STATUS_UNSPECIFIED": 0,
		"PAIR_STATUS_PAIRED":      1,
		"PAIR_STATUS_PENDING":     2,
	}
)

func (x PairStatus) Enum() *PairStatus {
	p := new(PairStatus)
	*p = x
	return p
}

func (x PairStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PairStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_asamesh_v1_peer_proto_enumTypes[1].Descriptor()
}

func (PairStatus) Type() protoreflect.EnumType {
	return &file_asamesh_v1_peer_proto_enumTypes[1]
}

func (x PairStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PairStatus.Descriptor instead.
func (PairStatus) EnumDescriptor() ([]byte, []int) {
	return file_asamesh_v1_peer_proto_rawDescGZIP(), []int{1}
}

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities  []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_asamesh_v1_peer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_peer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_peer_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HelloRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type HelloResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Version      string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Capabilities []string               `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// 对方授予调用者的角色；未授权为 ROLE_NONE。
	GrantedRole Role `protobuf:"varint,3,opt,name=granted_role,json=grantedRole,proto3,enum=asamesh.v1.Role" json:"granted_role,omitempty"`
	// 只对已授权的身份填写。
	Label         string `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_asamesh_v1_peer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_peer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_peer_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HelloResponse) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *HelloResponse) GetGrantedRole() Role {
	if x != nil {
		return x.GrantedRole
	}
	return Role_ROLE_NONE
}

func (x *HelloResponse) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type PairRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 邀请编号与一次性密钥；都为空 = 申请-批准。
	InviteId     string `protobuf:"bytes,1,opt,name=invite_id,json=inviteId,proto3" json:"invite_id,omitempty"`
	InviteSecret []byte `protobuf:"bytes,2,opt,name=invite_secret,json=inviteSecret,proto3" json:"invite_secret,omitempty"`
	// 调用者的备注名与版本（显示在对方的待批准列表里）。
	Label         string `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Version       string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairRequest) Reset() {
	*x = PairRequest{}
	mi := &file_asamesh_v1_peer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairRequest) ProtoMessage() {}

func (x *PairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_peer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairRequest.ProtoReflect.Descriptor instead.
func (*PairRequest) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_peer_proto_rawDescGZIP(), []int{2}
}

func (x *PairRequest) GetInviteId() string {
	if x != nil {
		return x.InviteId
	}
	return ""
}

func (x *PairRequest) GetInviteSecret() []byte {
	if x != nil {
		return x.InviteSecret
	}
	return nil
}

func (x *PairRequest) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *PairRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type PairResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Status      PairStatus             `protobuf:"varint,1,opt,name=status,proto3,enum=asamesh.v1.PairStatus" json:"status,omitempty"`
	GrantedRole Role                   `protobuf:"varint,2,opt,name=granted_role,json=grantedRole,proto3,enum=asamesh.v1.Role" json:"granted_role,omitempty"`
	// 对方的备注名（只在 PAIRED 时填写）。
	Label         string `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairResponse) Reset() {
	*x = PairResponse{}
	mi := &file_asamesh_v1_peer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairResponse) ProtoMessage() {}

func (x *PairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_peer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairResponse.ProtoReflect.Descriptor instead.
func (*PairResponse) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_peer_proto_rawDescGZIP(), []int{3}
}

func (x *PairResponse) GetStatus() PairStatus {
	if x != nil {
		return x.Status
	}
	return PairStatus_PAIR_STATUS_UNSPECIFIED
}

func (x *PairResponse) GetGrantedRole() Role {
	if x != nil {
		return x.GrantedRole
	}
	return Role_ROLE_NONE
}

func (x *PairResponse) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// HTTPFrame 是隧道流上的信封。A→B：request，然后 body*，然后 end；协议升级（WebSocket）之后
// A→B 继续发 body。B→A：response，然后 body*，然后 end；或者连接被劫持时直接发 raw（含 101 响应行）。
type HTTPFrame struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*HTTPFrame_Request
	//	*HTTPFrame_Response
	//	*HTTPFrame_Body
	//	*HTTPFrame_End
	//	*HTTPFrame_Raw
	Msg           isHTTPFrame_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPFrame) Reset() {
	*x = HTTPFrame{}
	mi := &file_asamesh_v1_peer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPFrame) ProtoMessage() {}

func (x *HTTPFrame) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_peer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPFrame.ProtoReflect.Descriptor instead.
func (*HTTPFrame) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_peer_proto_rawDescGZIP(), []int{4}
}

func (x *HTTPFrame) GetMsg() isHTTPFrame_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *HTTPFrame) GetRequest() *HTTPRequestHead {
	if x != nil {
		if x, ok := x.Msg.(*HTTPFrame_Request); ok {
			return x.Request
		}
	}
	return nil
}

func (x *HTTPFrame) GetResponse() *HTTPResponseHead {
	if x != nil {
		if x, ok := x.Msg.(*HTTPFrame_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *HTTPFrame) GetBody() []byte {
	if x != nil {
		if x, ok := x.Msg.(*HTTPFrame_Body); ok {
			return x.Body
		}
	}
	return nil
}

func (x *HTTPFrame) GetEnd() *HTTPBodyEnd {
	if x != nil {
		if x, ok := x.Msg.(*HTTPFrame_End); ok {
			return x.End
		}
	}
	return nil
}

func (x *HTTPFrame) GetRaw() []byte {
	if x != nil {
		if x, ok := x.Msg.(*HTTPFrame_Raw); ok {
			return x.Raw
		}
	}
	return nil
}

type isHTTPFrame_Msg interface {
	isHTTPFrame_Msg()
}

type HTTPFrame_Request struct {
	Request *HTTPRequestHead `protobuf:"bytes,1,opt,name=request,proto3,oneof"`
}

type HTTPFrame_Response struct {
	Response *HTTPResponseHead `protobuf:"bytes,2,opt,name=response,proto3,oneof"`
}

type HTTPFrame_Body struct {
	Body []byte `protobuf:"bytes,3,opt,name=body,proto3,oneof"`
}

type HTTPFrame_End struct {
	// 发送方的 body 结束。不用 CloseSend：协议升级后 A 还要继续发数据。
	End *HTTPBodyEnd `protobuf:"bytes,4,opt,name=end,proto3,oneof"`
}

type HTTPFrame_Raw struct {
	// B→A：连接被劫持之后的原始字节，由 A 解析出 101 响应。
	Raw []byte `protobuf:"bytes,5,opt,name=raw,proto3,oneof"`
}

func (*HTTPFrame_Request) isHTTPFrame_Msg() {}

func (*HTTPFrame_Response) isHTTPFrame_Msg() {}

func (*HTTPFrame_Body) isHTTPFrame_Msg() {}

func (*HTTPFrame_End) isHTTPFrame_Msg() {}

func (*HTTPFrame_Raw) isHTTPFrame_Msg() {}

type HTTPRequestHead struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Method string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	// 已转义的路径（以 / 开头）与查询串（不含 ?）。
	Path     string        `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	RawQuery string        `protobuf:"bytes,3,opt,name=raw_query,json=rawQuery,proto3" json:"raw_query,omitempty"`
	Headers  []*HTTPHeader `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty"`
	// A 上发起者的用户名。B 只用于审计，**不**作为授权依据。
	RemoteUser    string `protobuf:"bytes,5,opt,name=remote_user,json=remoteUser,proto3" json:"remote_user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPRequestHead) Reset() {
	*x = HTTPRequestHead{}
	mi := &file_asamesh_v1_peer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPRequestHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPRequestHead) ProtoMessage() {}

func (x *HTTPRequestHead) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_peer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPRequestHead.ProtoReflect.Descriptor instead.
func (*HTTPRequestHead) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_peer_proto_rawDescGZIP(), []int{5}
}

func (x *HTTPRequestHead) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HTTPRequestHead) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *HTTPRequestHead) GetRawQuery() string {
	if x != nil {
		return x.RawQuery
	}
	return ""
}

func (x *HTTPRequestHead) GetHeaders() []*HTTPHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPRequestHead) GetRemoteUser() string {
	if x != nil {
		return x.RemoteUser
	}
	return ""
}

type HTTPResponseHead struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Headers       []*HTTPHeader          `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPResponseHead) Reset() {
	*x = HTTPResponseHead{}
	mi := &file_asamesh_v1_peer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPResponseHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPResponseHead) ProtoMessage() {}

func (x *HTTPResponseHead) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_peer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPResponseHead.ProtoReflect.Descriptor instead.
func (*HTTPResponseHead) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_peer_proto_rawDescGZIP(), []int{6}
}

func (x *HTTPResponseHead) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HTTPResponseHead) GetHeaders() []*HTTPHeader {
	if x != nil {
		return x.Headers
	}
	return nil
}

type HTTPHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values        []string               `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPHeader) Reset() {
	*x = HTTPHeader{}
	mi := &file_asamesh_v1_peer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPHeader) ProtoMessage() {}

func (x *HTTPHeader) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_peer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPHeader.ProtoReflect.Descriptor instead.
func (*HTTPHeader) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_peer_proto_rawDescGZIP(), []int{7}
}

func (x *HTTPHeader) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HTTPHeader) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

type HTTPBodyEnd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HTTPBodyEnd) Reset() {
	*x = HTTPBodyEnd{}
	mi := &file_asamesh_v1_peer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HTTPBodyEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPBodyEnd) ProtoMessage() {}

func (x *HTTPBodyEnd) ProtoReflect() protoreflect.Message {
	mi := &file_asamesh_v1_peer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPBodyEnd.ProtoReflect.Descriptor instead.
func (*HTTPBodyEnd) Descriptor() ([]byte, []int) {
	return file_asamesh_v1_peer_proto_rawDescGZIP(), []int{8}
}

var File_asamesh_v1_peer_proto protoreflect.FileDescriptor

const file_asamesh_v1_peer_proto_rawDesc = "" +
	"\n" +
	"\x15asamesh/v1/peer.proto\x12\n" +
	"asamesh.v1\"L\n" +
	"\fHelloRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\"\x98\x01\n" +
	"\rHelloResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\"\n" +
	"\fcapabilities\x18\x02 \x03(\tR\fcapabilities\x123\n" +
	"\fgranted_role\x18\x03 \x01(\x0e2\x10.asamesh.v1.RoleR\vgrantedRole\x12\x14\n" +
	"\x05label\x18\x04 \x01(\tR\x05label\"\x7f\n" +
	"\vPairRequest\x12\x1b\n" +
	"\tinvite_id\x18\x01 \x01(\tR\binviteId\x12#\n" +
	"\rinvite_secret\x18\x02 \x01(\fR\finviteSecret\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\x89\x01\n" +
	"\fPairResponse\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x16.asamesh.v1.PairStatusR\x06status\x123\n" +
	"\fgranted_role\x18\x02 \x01(\x0e2\x10.asamesh.v1.RoleR\vgrantedRole\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\"\xde\x01\n" +
	"\tHTTPFrame\x127\n" +
	"\arequest\x18\x01 \x01(\v2\x1b.asamesh.v1.HTTPRequestHeadH\x00R\arequest\x12:\n" +
	"\bresponse\x18\x02 \x01(\v2\x1c.asamesh.v1.HTTPResponseHeadH\x00R\bresponse\x12\x14\n" +
	"\x04body\x18\x03 \x01(\fH\x00R\x04body\x12+\n" +
	"\x03end\x18\x04 \x01(\v2\x17.asamesh.v1.HTTPBodyEndH\x00R\x03end\x12\x12\n" +
	"\x03raw\x18\x05 \x01(\fH\x00R\x03rawB\x05\n" +
	"\x03msg\"\xad\x01\n" +
	"\x0fHTTPRequestHead\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1b\n" +
	"\traw_query\x18\x03 \x01(\tR\brawQuery\x120\n" +
	"\aheaders\x18\x04 \x03(\v2\x16.asamesh.v1.HTTPHeaderR\aheaders\x12\x1f\n" +
	"\vremote_user\x18\x05 \x01(\tR\n" +
	"remoteUser\"\\\n" +
	"\x10HTTPResponseHead\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x120\n" +
	"\aheaders\x18\x02 \x03(\v2\x16.asamesh.v1.HTTPHeaderR\aheaders\"8\n" +
	"\n" +
	"HTTPHeader\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06values\x18\x02 \x03(\tR\x06values\"\r\n" +
	"\vHTTPBodyEnd*8\n" +
	"\x04Role\x12\r\n" +
	"\tROLE_NONE\x10\x00\x12\x11\n" +
	"\rROLE_OPERATOR\x10\x01\x12\x0e\n" +
	"\n" +
	"ROLE_ADMIN\x10\x02*Z\n" +
	"\n" +
	"PairStatus\x12\x1b\n" +
	"\x17PAIR_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12PAIR_STATUS_PAIRED\x10\x01\x12\x17\n" +
	"\x13PAIR_STATUS_PENDING\x10\x022\xb9\x01\n" +
	"\x04Peer\x12<\n" +
	"\x05Hello\x12\x18.asamesh.v1.HelloRequest\x1a\x19.asamesh.v1.HelloResponse\x129\n" +
	"\x04Pair\x12\x17.asamesh.v1.PairRequest\x1a\x18.asamesh.v1.PairResponse\x128\n" +
	"\x04HTTP\x12\x15.asamesh.v1.HTTPFrame\x1a\x15.asamesh.v1.HTTPFrame(\x010\x01B(Z&asa-server/internal/mesh/meshpb;meshpbb\x06proto3"

var (
	file_asamesh_v1_peer_proto_rawDescOnce sync.Once
	file_asamesh_v1_peer_proto_rawDescData []byte
)

func file_asamesh_v1_peer_proto_rawDescGZIP() []byte {
	file_asamesh_v1_peer_proto_rawDescOnce.Do(func() {
		file_asamesh_v1_peer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_asamesh_v1_peer_proto_rawDesc), len(file_asamesh_v1_peer_proto_rawDesc)))
	})
	return file_asamesh_v1_peer_proto_rawDescData
}

var file_asamesh_v1_peer_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_asamesh_v1_peer_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_asamesh_v1_peer_proto_goTypes = []any{
	(Role)(0),                // 0: asamesh.v1.Role
	(PairStatus)(0),          // 1: asamesh.v1.PairStatus
	(*HelloRequest)(nil),     // 2: asamesh.v1.HelloRequest
	(*HelloResponse)(nil),    // 3: asamesh.v1.HelloResponse
	(*PairRequest)(nil),      // 4: asamesh.v1.PairRequest
	(*PairResponse)(nil),     // 5: asamesh.v1.PairResponse
	(*HTTPFrame)(nil),        // 6: asamesh.v1.HTTPFrame
	(*HTTPRequestHead)(nil),  // 7: asamesh.v1.HTTPRequestHead
	(*HTTPResponseHead)(nil), // 8: asamesh.v1.HTTPResponseHead
	(*HTTPHeader)(nil),       // 9: asamesh.v1.HTTPHeader
	(*HTTPBodyEnd)(nil),      // 10: asamesh.v1.HTTPBodyEnd
}
var file_asamesh_v1_peer_proto_depIdxs = []int32{
	0,  // 0: asamesh.v1.HelloResponse.granted_role:type_name -> asamesh.v1.Role
	1,  // 1: asamesh.v1.PairResponse.status:type_name -> asamesh.v1.PairStatus
	0,  // 2: asamesh.v1.PairResponse.granted_role:type_name -> asamesh.v1.Role
	7,  // 3: asamesh.v1.HTTPFrame.request:type_name -> asamesh.v1.HTTPRequestHead
	8,  // 4: asamesh.v1.HTTPFrame.response:type_name -> asamesh.v1.HTTPResponseHead
	10, // 5: asamesh.v1.HTTPFrame.end:type_name -> asamesh.v1.HTTPBodyEnd
	9,  // 6: asamesh.v1.HTTPRequestHead.headers:type_name -> asamesh.v1.HTTPHeader
	9,  // 7: asamesh.v1.HTTPResponseHead.headers:type_name -> asamesh.v1.HTTPHeader
	2,  // 8: asamesh.v1.Peer.Hello:input_type -> asamesh.v1.HelloRequest
	4,  // 9: asamesh.v1.Peer.Pair:input_type -> asamesh.v1.PairRequest
	6,  // 10: asamesh.v1.Peer.HTTP:input_type -> asamesh.v1.HTTPFrame
	3,  // 11: asamesh.v1.Peer.Hello:output_type -> asamesh.v1.HelloResponse
	5,  // 12: asamesh.v1.Peer.Pair:output_type -> asamesh.v1.PairResponse
	6,  // 13: asamesh.v1.Peer.HTTP:output_type -> asamesh.v1.HTTPFrame
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_asamesh_v1_peer_proto_init() }
func file_asamesh_v1_peer_proto_init() {
	if File_asamesh_v1_peer_proto != nil {
		return
	}
	file_asamesh_v1_peer_proto_msgTypes[4].OneofWrappers = []any{
		(*HTTPFrame_Request)(nil),
		(*HTTPFrame_Response)(nil),
		(*HTTPFrame_Body)(nil),
		(*HTTPFrame_End)(nil),
		(*HTTPFrame_Raw)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_asamesh_v1_peer_proto_rawDesc), len(file_asamesh_v1_peer_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_asamesh_v1_peer_proto_goTypes,
		DependencyIndexes: file_asamesh_v1_peer_proto_depIdxs,
		EnumInfos:         file_asamesh_v1_peer_proto_enumTypes,
		MessageInfos:      file_asamesh_v1_peer_proto_msgTypes,
	}.Build()
	File_asamesh_v1_peer_proto = out.File
	file_asamesh_v1_peer_proto_goTypes = nil
	file_asamesh_v1_peer_proto_depIdxs = nil
}
