// 管理器 ↔ 管理器。跑在端到端 mTLS 之上（直连或经中转），见
// docs/REMOTE_MANAGER_MESH_PLAN.md §5.5、§12 P1-1、P3-3、P3-4、P6。
//
// 兼容规则同 coordinator.proto：只做向后兼容的增量，字段号永不复用。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: asamesh/v1/peer.proto

package meshpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Peer_Hello_FullMethodName = "/asamesh.v1.Peer/Hello"
	Peer_Pair_FullMethodName  = "/asamesh.v1.Peer/Pair"
	Peer_HTTP_FullMethodName  = "/asamesh.v1.Peer/HTTP"
	Peer_Punch_FullMethodName = "/asamesh.v1.Peer/Punch"
)

// PeerClient is the client API for Peer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PeerClient interface {
	// 版本、能力列表、对方授予我的角色。未配对的身份也能调用。
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	// 配对：带邀请码直接完成，不带则提交一条待批准的申请。未配对的身份也能调用。
	Pair(ctx context.Context, in *PairRequest, opts ...grpc.CallOption) (*PairResponse, error)
	// HTTP 隧道：一个 HTTP 请求 = 一条流（§7）。只对已授权的身份开放。
	HTTP(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HTTPFrame, HTTPFrame], error)
	// 打洞信令（§12 P6-3）：只在中转路径上调用。调用者带上自己的 UDP 候选与探测密钥，
	// 被叫方回自己的候选并立即开始探测。只对已授权的身份开放；本机关了打洞时返回 FailedPrecondition。
	Punch(ctx context.Context, in *PunchRequest, opts ...grpc.CallOption) (*PunchResponse, error)
}

type peerClient struct {
	cc grpc.ClientConnInterface
}

func NewPeerClient(cc grpc.ClientConnInterface) PeerClient {
	return &peerClient{cc}
}

func (c *peerClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, Peer_Hello_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerClient) Pair(ctx context.Context, in *PairRequest, opts ...grpc.CallOption) (*PairResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PairResponse)
	err := c.cc.Invoke(ctx, Peer_Pair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *peerClient) HTTP(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[HTTPFrame, HTTPFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Peer_ServiceDesc.Streams[0], Peer_HTTP_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HTTPFrame, HTTPFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Peer_HTTPClient = grpc.BidiStreamingClient[HTTPFrame, HTTPFrame]

func (c *peerClient) Punch(ctx context.Context, in *PunchRequest, opts ...grpc.CallOption) (*PunchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PunchResponse)
	err := c.cc.Invoke(ctx, Peer_Punch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PeerServer is the server API for Peer service.
// All implementations must embed UnimplementedPeerServer
// for forward compatibility.
type PeerServer interface {
	// 版本、能力列表、对方授予我的角色。未配对的身份也能调用。
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	// 配对：带邀请码直接完成，不带则提交一条待批准的申请。未配对的身份也能调用。
	Pair(context.Context, *PairRequest) (*PairResponse, error)
	// HTTP 隧道：一个 HTTP 请求 = 一条流（§7）。只对已授权的身份开放。
	HTTP(grpc.BidiStreamingServer[HTTPFrame, HTTPFrame]) error
	// 打洞信令（§12 P6-3）：只在中转路径上调用。调用者带上自己的 UDP 候选与探测密钥，
	// 被叫方回自己的候选并立即开始探测。只对已授权的身份开放；本机关了打洞时返回 FailedPrecondition。
	Punch(context.Context, *PunchRequest) (*PunchResponse, error)
	mustEmbedUnimplementedPeerServer()
}

// UnimplementedPeerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPeerServer struct{}

func (UnimplementedPeerServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (UnimplementedPeerServer) Pair(context.Context, *PairRequest) (*PairResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Pair not implemented")
}
func (UnimplementedPeerServer) HTTP(grpc.BidiStreamingServer[HTTPFrame, HTTPFrame]) error {
	return status.Errorf(codes.Unimplemented, "method HTTP not implemented")
}
func (UnimplementedPeerServer) Punch(context.Context, *PunchRequest) (*PunchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Punch not implemented")
}
func (UnimplementedPeerServer) mustEmbedUnimplementedPeerServer() {}
func (UnimplementedPeerServer) testEmbeddedByValue()              {}

// UnsafePeerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PeerServer will
// result in compilation errors.
type UnsafePeerServer interface {
	mustEmbedUnimplementedPeerServer()
}

func RegisterPeerServer(s grpc.ServiceRegistrar, srv PeerServer) {
	// If the following call pancis, it indicates UnimplementedPeerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Peer_ServiceDesc, srv)
}

func _Peer_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Peer_Hello_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Peer_Pair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServer).Pair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Peer_Pair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServer).Pair(ctx, req.(*PairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Peer_HTTP_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PeerServer).HTTP(&grpc.GenericServerStream[HTTPFrame, HTTPFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Peer_HTTPServer = grpc.BidiStreamingServer[HTTPFrame, HTTPFrame]

func _Peer_Punch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PunchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PeerServer).Punch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Peer_Punch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PeerServer).Punch(ctx, req.(*PunchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Peer_ServiceDesc is the grpc.ServiceDesc for Peer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Peer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "asamesh.v1.Peer",
	HandlerType: (*PeerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _Peer_Hello_Handler,
		},
		{
			MethodName: "Pair",
			Handler:    _Peer_Pair_Handler,
		},
		{
			MethodName: "Punch",
			Handler:    _Peer_Punch_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "HTTP",
			Handler:       _Peer_HTTP_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "asamesh/v1/peer.proto",
}
